### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ice-chillios** [Selleo/merit-money-api#8]
- Deploy:
  - [x] Heroku instance
  - [x] Setup mongo db
  - [ ] Backgroun Worker
  - [x] Set ENV

- Users:
  - [x] Model
  - [x] Authorization
  - [x] Creating User with token (JWT)

- Organizations:
  - [x] Model
  - [x] Creating Organization
  - [x] Adding User to organization
  - [x] Listing Users of organization
  - [x] Settings of organisation (how many kudo per which period)

- Kudos:
  - [x] Model
  - [x] Listing all kudos per user.
  - [x] Listing all kudos per organization.
  - [x] Creating kudos.

- Graphql:
  - [x] Mutations for User
  - [x] Mutations for Organization
  - [x] Mutations for Kudo
  - [x] Queries for User
  - [x] Queries for Organization
  - [x] Queries for Kudo
  - [x] Validation in data (Kudo can't be created without organization_id, giver or receiver)

- Admin panel (optional - future):
  - [ ] React app to rule them all.
  - [ ] Setup express to use policies, authentication.
